### ISSUE TITLE
[Plugin][Bug]: The plugin cannot be installed

### ISSUE THREAD

**Issue by yodahuang** [ObsidianPublisher/obsidian-github-publisher#171]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Plugin version

6.2.1

### Describe the bug

- With the plugin previously installed, when click "update", it tells that it cannot be updated.
- Uninstall the plugin and reinstall it, Obsidian tells me it fails. Inspecting developer console, it tells
```
Error: Request failed, status 404
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
```

### Minimal Reproducible Example

I'm not in the state that I need a note yet.

### Configuration

```JSON
I'm not in the state of needing an export config yet.
```

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:29:35 PDT 2023; root:xnu-8796.121.3~8/RELEASE_ARM64_T6020 22.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.11
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 11
		1: Auto Glossary v0.9.0
		2: Completr v3.2.0
		3: Contextual Typography v2.2.5
		4: Emoji Toolbar v0.4.1
		5: Hider v1.2.4
		6: Kanban v1.5.3
		7: Minimal Theme Settings v6.3.1
		8: Quick Latex for Obsidian v2.6.2
		9: Remotely Save v0.3.25
		10: Text Format v2.2.1
		11: Style Settings v1.0.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Lisandra-dev** [comment]
Oh, thanks. Didn't notice my release wasn't made. In fact, Obsidian try to install using the tag, so if no release is attached, it crash.

**Comment by Lisandra-dev** [comment]
fixed
